citygarden_web-dev-mongodb:
  container_name: citygarden_web-dev-mongodb
  image: mongo:3.0.7
  # volumes:
  #   - ~/volumes/jhipster/citygarden_web/dev-mongodb/:/data/db/
  ports:
    - "27017:27017"
